CREATE DATABASE  BD_AIR_MAROC;
CREATE TABLE PILOTE(
    NUMPIL INT AUTO_INCREMENT PRIMARY KEY,
    NOMPIL VARCHAR(50) NOT NULL,
    VILLE VARCHAR(20),
    SALAIRE INT 
);
CREATE TABLE AVION (
    NUMAV INT AUTO_INCREMENT PRIMARY KEY,
    NOMAV VARCHAR(20),
    CAPACITE DECIMAL (10,2),
    VILLE_ORI VARCHAR(20)
);
CREATE TABLE VOL(
    NUMVOL INT AUTO_INCREMENT PRIMARY KEY,
    VILLE_DEP VARCHAR(20),
    VILLE_ARR VARCHAR(20),
    H_DEP TIME ,
    H_ARR TIME,
    NUMPIL INT,
    NUMAV INT,
    FOREIGN KEY (NUMPIL) REFERENCES PILOTE(NUMPIL),
    FOREIGN KEY (NUMAV) REFERENCES AVION(NUMAV)
);

INSERT INTO PILOTE (NOMPIL, VILLE, SALAIRE) VALUES 
('Alami', 'Marrakech', 25000),
('Benani', 'Meknès', 22000),
('Chakiri', 'Casablanca', 18000),
('Drissi', 'Meknès', 15000),
('Fassi', 'Fès', 30000),
('Guerrouj', 'Marrakech', 12000), -- ID 6 : Pour tester les salaires bas
('Zairi', 'Rabat', 19000);

INSERT INTO AVION (NOMAV, CAPACITE, VILLE_ORI) VALUES 
('Boeing 747', 400, 'Marrakech'),
('Airbus A320', 150, 'Casablanca'),
('ATR 72', 70, 'Marrakech'),
('Boeing 777', 380, 'Tanger'),
('Airbus A380', 500, 'Agadir'),
('Boeing 737', 180, 'Agadir'), -- ID 101 : Indispensable pour la Question 19
('Falcon 900', 20, 'Tanger'); ;

INSERT INTO VOL (VILLE_DEP, VILLE_ARR, H_DEP, H_ARR, NUMPIL, NUMAV) VALUES 
('Marrakech', 'Paris', '08:00:00', '11:30:00', 1, 1), -- Pilote Alami, Boeing 747
('Meknès', 'Madrid', '14:00:00', '16:00:00', 2, 4),   -- Pilote Benani, Boeing 777
('Marrakech', 'Lyon', '10:00:00', '13:00:00', 2, 3),   -- Pilote Benani (de Meknès), au départ de Marrakech
('Casablanca', 'Rome', '20:00:00', '23:00:00', 3, 2),  -- Pilote Chakiri, Airbus A320
('Guelmim', 'Agadir', '09:00:00', '10:00:00', 4, 3)   -- Pilote Drissi, ATR 72
('Agadir', 'Dakhla', '11:30:00', '13:00:00', 1, 5),   -- Vol 6 : Fait suite au vol de Guelmim (Q10)
('Casablanca', 'Oujda', '15:00:00', '16:30:00', 3, 2), -- Vol 7 : Départ Casa (Q14)
('Marrakech', 'Fès', '07:00:00', '08:15:00', 6, 101);


INSERT INTO AVION (NOMAV, CAPACITE, VILLE_ORI) VALUES 
('Boeing 737', 180, 'Agadir'), 
('Falcon 900', 20, 'Tanger');    

INSERT INTO PILOTE (NOMPIL, VILLE, SALAIRE) VALUES 
('Guerrouj', 'Marrakech', 12000), 
('Zairi', 'Rabat', 19000);        

INSERT INTO VOL (VILLE_DEP, VILLE_ARR, H_DEP, H_ARR, NUMPIL, NUMAV) VALUES 
('Agadir', 'Dakhla', '11:30:00', '13:00:00', 1, 5),   
('Casablanca', 'Oujda', '15:00:00', '16:30:00', 3, 2), 
('Marrakech', 'Fès', '07:00:00', '08:15:00', 6, 4); 
INSERT INTO AVION (NOMAV, CAPACITE, VILLE_ORI) VALUES 
('Boeing 737', 180, 'Agadir'), 
('Falcon 900', 20, 'Tanger');    

INSERT INTO PILOTE (NOMPIL, VILLE, SALAIRE) VALUES 
('Guerrouj', 'Marrakech', 12000), 
('Zairi', 'Rabat', 19000);        

INSERT INTO VOL (VILLE_DEP, VILLE_ARR, H_DEP, H_ARR, NUMPIL, NUMAV) VALUES 
('Agadir', 'Dakhla', '11:30:00', '13:00:00', 1, 5),   
('Casablanca', 'Oujda', '15:00:00', '16:30:00', 3, 2), 
('Marrakech', 'Fès', '07:00:00', '08:15:00', 6, 4); 


-- REQUETE
SELECT * FROM AVION WHERE CAPACITE > 350;
SELECT NUMAV, NOMAV FROM AVION WHERE VILLE_ORI = 'Marrakech';
SELECT DISTINCT NUMPIL, VILLE_DEP FROM VOL;
SELECT * FROM PILOTE;
SELECT NOMPIL FROM PILOTE WHERE VILLE = 'Meknès' AND SALAIRE > 20000;
SELECT NUMAV, NOMAV FROM AVION WHERE VILLE = 'Marrakech' OR CAPACITE < 350;
SELECT NUMPIL FROM PILOTE WHERE NUMPIL NOT IN (SELECT NUMPIL FROM VOL);
SELECT V.NUMVOL FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL WHERE V.VILLE_DEP = 'Marrakech' AND P.VILLE = 'Meknès';
SELECT V.NUMVOL FROM VOL V JOIN AVION A ON V.NUMAV = A.NUMAV WHERE A.VILLE_ORI != 'Marrakech';
SELECT DISTINCT VILLE_ARR FROM VOL WHERE VILLE_DEP IN (SELECT VILLE_ARR FROM VOL WHERE VILLE_DEP = 'Guelmim');
SELECT P.NOMPIL, V.NUMVOL FROM PILOTE P JOIN VOL V ON P.NUMPIL = V.NUMPIL;
SELECT DISTINCT P.NOMPIL, A.NOMAV FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL JOIN AVION A ON V.NUMAV = A.NUMAV;
SELECT V.NUMVOL, V.VILLE_DEP, V.VILLE_ARR, P.NOMPIL FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL;
SELECT DISTINCT A.NOMAV FROM AVION A JOIN VOL V ON A.NUMAV = V.NUMAV WHERE V.VILLE_DEP = 'Casablanca';
SELECT DISTINCT P.NOMPIL FROM PILOTE P JOIN VOL V ON P.NUMPIL = V.NUMPIL JOIN AVION A ON V.NUMAV = A.NUMAV WHERE A.CAPACITE > 300;
SELECT P.NOMPIL, V.VILLE_ARR FROM PILOTE P JOIN VOL V ON P.NUMPIL = V.NUMPIL;
SELECT * FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL JOIN AVION A ON V.NUMAV = A.NUMAV;
SELECT NOMPIL FROM PILOTE WHERE SALAIRE > (SELECT AVG(SALAIRE) FROM PILOTE);
SELECT * FROM AVION WHERE CAPACITE > (SELECT CAPACITE FROM AVION WHERE NUMAV = 7);
SELECT * FROM PILOTE WHERE NUMPIL NOT IN (SELECT NUMPIL FROM VOL);
SELECT DISTINCT V.VILLE_DEP FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL WHERE P.VILLE = 'Marrakech';
CREATE VIEW V_VOL_COMPLET AS SELECT V.NUMVOL, P.NOMPIL, A.NOMAV FROM VOL V JOIN PILOTE P ON V.NUMPIL = P.NUMPIL JOIN AVION A ON V.NUMAV = A.NUMAV;
CREATE VIEW V_PILOTE_RICHES AS SELECT * FROM PILOTE WHERE SALAIRE > 15000;
SELECT * FROM V_PILOTE_RICHES;
DROP VIEW V_PILOTE_RICHES;
CREATE USER 'user_air'@'localhost' IDENTIFIED BY 'password123';
GRANT SELECT ON BD_AIR_MAROC.PILOTE TO 'user_air'@'localhost';
GRANT INSERT ON BD_AIR_MAROC.VOL TO 'user_air'@'localhost';
REVOKE DELETE ON BD_AIR_MAROC.AVION FROM 'user_air'@'localhost';
GRANT ALL PRIVILEGES ON BD_AIR_MAROC.* TO 'user_air'@'localhost';
CREATE ROLE 'gestion_vol';--32
GRANT ALL ON BD_AIR_MAROC.VOL TO 'gestion_vol';--32
GRANT 'gestion_vol' TO 'user_air'@'localhost';